
<?php
/**
 * Route table. Generated by `D:\xampp\htdocs\generator.php` at 2020-10-23 11:58:15.
 * YOU DON'T HAVE TO MODIFY THIS FILE, JUST GENERATE IT :)
 */

$apiPost = new \App\Api\Post();
Flight::route('POST ../post', array($apiPost, 'create'));
Flight::route('GET ../post/@id', array($apiPost, 'get'));

$apiWelcome = new \App\Api\Welcome();
Flight::route('GET ../', array($apiWelcome, 'index'));

